/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg: '#F5F0E7',
        card: '#FCF8F1',
        primary: '#B65F47',
        secondary: '#4F745E',
        accent: '#A66F2C',
        error: '#A9473D',
        warning: '#B98231',
        ink: '#2A2723',
        muted: '#756E65',
        line: '#D9D0C3',
        'bg-dark': '#181613',
        'card-dark': '#211E1A',
        'elevated-dark': '#2B2722',
        'primary-dark': '#D9866D',
        'secondary-dark': '#7EAA8B',
        'accent-dark': '#C8934B',
        'error-dark': '#E07A6C',
        'warning-dark': '#D2A154',
        'ink-dark': '#F3ECE1',
        'muted-dark': '#B6AA9C',
        'line-dark': '#3C3730',
      },
      fontFamily: {
        sans: ['Outfit_400Regular'],
        medium: ['Outfit_500Medium'],
        semibold: ['Outfit_600SemiBold'],
        bold: ['Outfit_700Bold'],
        extrabold: ['Outfit_800ExtraBold'],
      },
    },
  },
  plugins: [],
};
